sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t riverron/docker-flask .
  - docker run -d -p 127.0.0.1:8000:8000 riverron/docker-flask /bin/sh -c "curl -v http://127.0.0.1:8000"
  - docker ps -a

script:
  - curl -v http://127.0.0.1:8000
