sudo: required

language: python

services:
  - docker

before_install:
  - docker-compose up -d
  - docker ps -a
  - curl -v http://127.0.0.1:8000/seed

install: true

script:
  - curl -v http://127.0.0.1:8000
